# Generated by Django 3.1.2 on 2020-10-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanManagement', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
