# Generated by Django 3.1.2 on 2020-10-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanManagement', '0006_auto_20201022_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='email',
        ),
    ]
