# Generated by Django 3.1.2 on 2020-10-22 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanManagement', '0008_auto_20201022_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
