# Generated by Django 3.1.2 on 2020-10-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanManagement', '0009_loan_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='email',
        ),
    ]
