# Generated by Django 3.1.2 on 2020-10-23 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanManagement', '0010_remove_loan_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='agentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
