# Generated by Django 3.1.2 on 2020-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanManagement', '0014_user_jwt_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount_required',
            new_name='loan_amount',
        ),
        migrations.AddField(
            model_name='loan',
            name='asset_value',
            field=models.FloatField(default=100000),
            preserve_default=False,
        ),
    ]
