# Generated by Django 3.1.2 on 2020-10-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanManagement', '0017_auto_20201029_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
    ]
